/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RapydApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const Data: core.schemas.ObjectSchema<Data.Raw, RapydApi.pointOfSale.Data> = core.schemas.object({
  tokenId: core.schemas.property("token_id", core.schemas.string()),
  operationId: core.schemas.property("operation_id", core.schemas.string()),
  accounts: core.schemas.list(core.schemas.lazyObject(() => serializers.pointOfSale.Account)),
});

export declare namespace Data {
  interface Raw {
    token_id: string;
    operation_id: string;
    accounts: serializers.pointOfSale.Account.Raw[];
  }
}
