/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RapydApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const EchoResponse: core.schemas.ObjectSchema<EchoResponse.Raw, RapydApi.pointOfSale.EchoResponse> =
  core.schemas.object({
    errorCode: core.schemas.property("error_code", core.schemas.string()),
    status: core.schemas.lazy(() => serializers.pointOfSale.StatusOptions),
    message: core.schemas.string(),
    operationId: core.schemas.property("operation_id", core.schemas.string()),
  });

export declare namespace EchoResponse {
  interface Raw {
    error_code: string;
    status: serializers.pointOfSale.StatusOptions.Raw;
    message: string;
    operation_id: string;
  }
}
