/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RapydApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const OpenSessionResponse: core.schemas.ObjectSchema<
  OpenSessionResponse.Raw,
  RapydApi.pointOfSale.OpenSessionResponse
> = core.schemas.object({
  status: core.schemas.lazyObject(() => serializers.pointOfSale.Status),
  data: core.schemas.lazyObject(() => serializers.pointOfSale.Data),
});

export declare namespace OpenSessionResponse {
  interface Raw {
    status: serializers.pointOfSale.Status.Raw;
    data: serializers.pointOfSale.Data.Raw;
  }
}
