/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RapydApi } from "../../..";
import * as core from "../../../core";

export const StatusOptions: core.schemas.Schema<StatusOptions.Raw, RapydApi.pointOfSale.StatusOptions> = core.schemas
  .string()
  .transform<RapydApi.pointOfSale.StatusOptions>({
    parse: (value) => RapydApi.pointOfSale.StatusOptions._parse(value),
    json: ({ value }) => value,
  });

export declare namespace StatusOptions {
  type Raw = string;
}
