/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RapydApi } from "../../..";
import * as core from "../../../core";

export interface Request {
  /** User one-time password code. */
  otpCode: string;
  /** ID of the point-of-sale location. */
  posId: string;
  /** Phone number of the wallet in E.164 format. */
  phoneNumber: string;
  /** Token ID received from Open Session. */
  tokenId: string;
}

export type Response = core.APIResponse<RapydApi.pointOfSale.CloseSessionResponse, RapydApi.pointOfSale.close.Error>;
export type Error = Error._Unknown;

export declare namespace Error {
  interface _Unknown extends _Utils {
    errorName: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <Result>(visitor: Error._Visitor<Result>) => Result;
  }

  interface _Visitor<Result> {
    _other: (value: core.Fetcher.Error) => Result;
  }
}
