/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RapydApi } from "../../..";

export interface Account {
  accountId: string;
  accountCurrency: RapydApi.pointOfSale.Currency;
  accountAlias: string;
  accountBalance: number;
}
