/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RapydApi } from "../../..";

export interface CloseSessionResponse {
  errorCode: string;
  status: RapydApi.pointOfSale.StatusOptions;
  message: string;
  operationId: string;
}
