/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RapydApi } from "../../..";

export interface Data {
  tokenId: string;
  operationId: string;
  accounts: RapydApi.pointOfSale.Account[];
}
