/**
 * This file auto-generated by Fern from our API Definition.
 */

import { RapydApi } from "../../..";

export interface OpenSessionResponse {
  status: RapydApi.pointOfSale.Status;
  data: RapydApi.pointOfSale.Data;
}
