/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Client as PointOfSaleClient } from "./resources/pointOfSale/client/Client";

export declare namespace RapydApiClient {
  interface Options {
    environment?: environments.Environment | string;
    auth?: {
      accessKey?: core.Supplier<string>;
    };
  }
}

export class RapydApiClient {
  constructor(private readonly options: RapydApiClient.Options) {}

  #pointOfSale: PointOfSaleClient | undefined;

  public get pointOfSale(): PointOfSaleClient {
    return (this.#pointOfSale ??= new PointOfSaleClient(this.options));
  }
}
