/**
 * This file auto-generated by Fern from our API Definition.
 */

export const Environment = {
  Production: "https://pos.rapyd.net",
  Sandbox: "https://sandboxapi.rapyd.net/v1/",
} as const;

export type Environment = typeof Environment.Production | typeof Environment.Sandbox;
